<?php  if($this->hasProductQAEnable()):?>
<?php  $questions = $this->getProductQuestions();?>
<div class="questionqa" id="questionqa">
	<div class="box-addanswer">
		<div class="fieldset">
			<div class="actions">
				<button type="submit" title="Ask Question?" class="action primary" id="product-askquestion-button" onclick='jQuery(".question-form").slideToggle()'>
					<span><?php  echo __('Ask Question?');?></span>
				</button>
			</div>
		</div>
		<div class="fieldset sortorder">
			<div class="qsearch-form fieldset">
				
				<div class="field">
					<label class="label" for="qasort"><?php  echo __('Search');?></label>
					<div class="control">
						<input type="text" name="q" id="qaq" placeholder="Search Question Here..." />
					</div>
				</div>

				
				<div class="submit control">
					<label class="label" for="qasort">&nbsp;</label>	
					<button type="button" id="qsearch" class="action primary"><span><?php  echo __('Search')?></span></button>
				</div>
			</div>
		</div>
		
		<div class="sortorder last">
			<div class="sorder-content fieldset">
				<div class="field">
				<label class="label" for="qasort"><?php  echo __('Sort By :');?></label>
					<select name="qasort" id="qasort" >
					<option value="<?php   echo $this->getSortUrl('latest')?>"><?php  echo __('Latest First')?></option>
					<option value="<?php   echo $this->getSortUrl('oldest')?>"><?php  echo __('Oldest First')?></option>
					<option value="<?php   echo $this->getSortUrl('mostlike')?>"><?php  echo __('Most Like')?></option>
					<option value="<?php   echo $this->getSortUrl('mostdislike')?>"><?php  echo __('Most Dislike')?></option>					
					</select>
				</div>
			</div>
		</div>
		
	
		<div id="question-message" class="messages"></div>
		<div class="fotorama__spinner"></div>
		<div class="question-form">
			<form action="<?php  echo $this->getFormUrl()?>" method="post" id="question-form">
				<input type="hidden" value="<?php  echo $this->getFormKey();?>" name="form_key"/>
				<fieldset class="fieldset">					
					<legend class="legend "><span><?php  echo __('You\'re Question')?> : </span><strong><?php  echo $this->getProduct()->getName()?></strong></legend>
					
					<div class="field required">
						<label class="label" for="name"> <?php  echo __('Name')?> : </label>
						<div class="control">
							<input type="text" id="name" class="input-text" required aria-required="true" value="<?php  echo trim($this->getCustomerName())?>" name="name">
						</div>						
					</div>
					<div class="field required">
						<label class="label" for="email"><?php  echo __('Email')?>:</label> 
						<div class="control">
							<input type="email" id="email" name="email" class="input-text" required aria-required="true"  value="<?php  echo $this->getCustomerEmail()?>">							
						</div>
					</div>
					<div class="field required">
						<label  class="label" for="question"><?php  echo __('Your Question')?></label> 
						<div class="control">
							<textarea name="question" id="question" maxlength="<?php  echo $this->getQuestionMaxCharacter()?>" minlength="15" required class="input-text" aria-required="true" name="question"></textarea>					
						</div>
					</div>
				</fieldset>
				<?php  echo $this->getChildHtml('qacaptcha'); ?>
				<div class="actions-toolbar"> 
					<div class="primary actions-primary">
						<button type="submit" required class="submit primary action"><span><?php  echo __('Submit Question')?></span></button>
					</div>
 					<div class="primary actions-primary">
						<button type="button" class="submit primary action" onclick='jQuery(".question-form").slideToggle()'><span><?php  echo __('Cancel')?></span></button>
					</div>
				</div>
			</form>			
		</div>
	</div>
	<div id="qasortquestion" class="questions-list">
		<div id="product_questions" class="questions">
			
			<?php  foreach($this->getProductQuestions() as $question):?>
			<div class="product_question" id="product_question-<?php  echo $question->getId() ?>">
					<div id="general-message" class="messages"></div>
					<div class="qheader">
						<div class="qtitle">
							<h3><?php  echo $question->getQuestion()?></h3>
						</div>
						<div class="actions">
							<a href="<?php  echo $this->getLikeActionUrl( $question->getId() )?>" class="like action"><img src="<?php  echo $block->getViewFileUrl('Bhavin_ProductQA::images/likes1.png'); ?>">(<span class="count"><?php  echo $question->getLikes()?></span>)</a>
							<a href="<?php  echo $this->getDislikeActionUrl( $question->getId() )?>" class="dislike action"><img src="<?php  echo $block->getViewFileUrl('Bhavin_ProductQA::images/dislike.png'); ?>">(<span class="count"><?php  echo  $question->getDislikes()?></span>)</a>
						</div>
						<div class="date-n-customer-name">
							<div class="name">
								<span><?php  echo $question->getName()?></span>
							</div>
							<div class="date">
								<span><?php  echo $this->formatDate($question->getCreatedAt())?></span>
							</div>	
						</div>
					</div>
					<div class="answers">
						<?php  echo $this->getQuestionsAnswer($question->getId() ); ?>
					</div>
			</div>	
			<?php  endforeach?>
			<?php  if(!count($questions)):?>
			<div class="no-result"><?php  echo __('No question found!');?></div>
			<?php  endif ?>
		</div>
	
		<div class="loadmorequestion questions"></div>
	</div>
	<?php  if($this->canShowLoadMore()):?>
	<div class="fieldset">
		<div class="actions">
			<button type="button" title="Load More..." class="  loadmorequestionbutton" data-totalpage="<?php  echo $this->getTotalPage()?>" data-url="<?php  echo $this->getLoadMoreUrl()?>" >
				<span><?php  echo __('Load More Question...');?></span>
			</button>
		</div>
	</div>
	<?php  endif?>
</div>
<script>
require(['productqa'],function($){});
</script>
<?php  endif?>
